import { prepareImports, importOptions, tableHeadings } from './workspace-import';
import { $, api, chart, download, esc, header, localEngine, metric, num, readFile, setup } from './workspace';
import { scene, mountScene } from './workspace-globe';

let generation=0;
let orbitMode='trajectory';
let contactMode='visibility';
let evidenceCase=0;
const field=(label:string,id:string,type:string,value:string,extra='')=>`<label class="field">${label}<input id="${id}" type="${type}" value="${esc(value)}" ${extra}/></label>`;
const fileField=(label:string,id:string,accept:string,help:string)=>`<label class="field">${label}<input id="${id}" type="file" accept="${accept}"/><small>${help}</small></label>`;
const val=(id:string)=>$(id) instanceof HTMLSelectElement? $<HTMLSelectElement>(id).value:$<HTMLInputElement>(id).value;
const nval=(id:string)=>Number(val(id));
const localNote=()=>`<p class="notice">${localEngine?'Connected to the engine on this PC. Selected files are sent only to this local process.':'Public reference mode. Open the local workspace to analyse your own files.'} No automatic saving.</p>`;
/** Said by the two tools that ship no example, because no real input for them exists here. */
const noExample=(needs:string)=>`<div class="plan-guidance"><p><strong>No example is supplied</strong>${needs} There is no real input for this tool in the repository, and an invented one would show the software running rather than working. <strong>This tool has not been exercised on real data.</strong></p></div>`;
const exampleLinks=(files:string[])=>`<div class="download-examples">${files.map(f=>`<a href="./examples/${f}" download>${f} ↓</a>`).join('')}</div>`;
const actions=()=>`<button class="secondary" id="setup-tool">${localEngine?'Local file guidance':'Run on this PC ↗'}</button>`;
function sourceDetails(r:any):string {
  const metadata = Array.isArray(r.metadata) ? r.metadata : r.metadata ? [r.metadata] : [];
  return `<details class="card details-panel"><summary>Inputs, methods and limitations</summary><div class="details-body"><p>Built ${esc(r.built_at)} · driftwatch ${esc(r.software_version)}. SHA-256 identifies the processed UTF-8 text; it does not verify the publisher.</p><ul class="source-list">${(r.sources||[]).map((s:any)=>`<li><strong>${esc(s.role)} · ${esc(s.name)}</strong><br/>${num(s.bytes,0)} bytes<br/><code>${esc(s.sha256)}</code></li>`).join('')}</ul>${metadata.map((m:any)=>`<p><strong>${esc(m.name)}</strong> · ${esc(m.format)}<br/>${esc(m.note||'')}${(m.import_warnings||[]).map((w:string)=>`<br/>${esc(w)}`).join('')}</p>`).join('')}${(r.limitations||[]).map((s:string)=>`<p>${esc(s)}</p>`).join('')}<p>Request fingerprint: <code>${esc(r.request_sha256)}</code></p></div></details>`;
}
function csv(rows:Record<string,unknown>[]):string {if(!rows.length)return '';const keys=Object.keys(rows[0]);const cell=(x:unknown)=>{let s=String(x??'');if(/^[=+@\-]/.test(s)&&typeof x!=='number')s="'"+s;return '"'+s.replaceAll('"','""')+'"';};return [keys.map(cell).join(','),...rows.map(r=>keys.map(k=>cell(r[k])).join(','))].join('\r\n');}
function exportButtons():string{return '<div class="export-actions no-print"><button class="primary" id="export-result">Save evidence JSON ↓</button><button class="secondary" id="export-csv">Save measurements CSV ↓</button><button class="secondary" id="print-result">Print report</button></div>';}
function bindExports(r:any,rows:Record<string,unknown>[]):void{$('export-result').onclick=()=>download(`driftwatch-${r.kind}.json`,r);$('export-csv').onclick=()=>download(`driftwatch-${r.kind}.csv`,csv(rows),'text/csv;charset=utf-8');$('print-result').onclick=()=>window.print();}
async function runRequest(kind:string,body:unknown,draw:(r:any)=>void,status:HTMLElement,button:HTMLButtonElement):Promise<void>{const g=++generation;button.disabled=true;status.className='status-line';status.textContent='Analysing locally…';try{const r=await api(kind,body);if(g!==generation||!document.contains(status))return;draw(r);status.textContent='Analysis complete. Save the result before leaving this tool.';}catch(e){if(g===generation){status.className='error';status.textContent=(e as Error).message;}}finally{button.disabled=false;}}
/** The two examples that exist. Both are measured or published data; see examples/README.md. */
const EXAMPLE_NOTE:Record<string,string>={
  compare:'Real data. ESA’s reconstructed precise orbit for Swarm A (NORAD 39452) against two Space-Track element sets for the same satellite issued six days apart, through the May 2024 storm. It is one satellite over one day, not a measure of the tool.',
  contacts:'Real data. Two Space-Track element sets for the ISS (NORAD 25544) over the published position of IGS station HRAO00ZAF at Hartebeesthoek. Predicted geometry only; no receiver log exists here, so nothing is matched against an observed lock.',
};
async function example(kind:string,draw:(r:any)=>void):Promise<void>{const g=generation;const status=$('form-status');status.className='status-line';status.textContent='Loading the measured example…';const button=$<HTMLButtonElement>('run-example');button.disabled=true;try{const name=kind==='compare'?'orbit':kind;const response=await fetch(`./examples/${name}-${localEngine?'request':'result'}.json`);if(!response.ok)throw new Error('The example file is unavailable. Rebuild it with scripts/export_workspace_examples.py.');const data=await response.json();const result=localEngine?await api(kind,data):data;if(g!==generation||!document.contains(status))return;result.demonstration=EXAMPLE_NOTE[kind];draw(result);status.textContent='Measured example loaded with its saved parameters. Form edits apply when you analyse selected files.';}catch(e){if(g===generation){status.className='error';status.textContent=(e as Error).message;}}finally{button.disabled=false;}}
function emptyResult(title:string,hint='Choose files from your PC. The globe will show the supplied track where the analysis contains positions.'):string{return `${scene()}<div class="card card-pad"><h2>${title}</h2><p class="card-sub">${hint}</p></div>`;}
export function renderTool(view:string):void{generation++;if(view==='orbits')orbits();else if(view==='contacts')contacts();else evidence();}

function orbits():void{
  const cdm=orbitMode==='cdm';
  $('content').innerHTML=header('Orbit product review','Find the reason for the disagreement.','Compare the same spacecraft at the same times. Inspect the reference frame and time system before treating a difference as a physical event.',actions())+`<div class="toolbar"><div class="segmented" role="group" aria-label="Comparison type"><button data-orbit-mode="trajectory" aria-pressed="${!cdm}">Orbit trajectories</button><button data-orbit-mode="cdm" aria-pressed="${cdm}">Conjunction messages</button></div><span class="card-sub">One closed case · all inputs stay on this PC</span></div><div class="tool-grid"><section class="card input-card"><form id="analysis-form"><h3>${cdm?'Reconcile two warnings':'Select the comparison'}</h3>${cdm?
    fileField('First conjunction message','first','.cdm,.kvn,.txt,.xml','CCSDS CDM, KVN or XML.')+fileField('Second conjunction message','second','.cdm,.kvn,.txt,.xml','A revision or another provider’s message.')+field('Closest-approach matching tolerance (seconds)','tca-tolerance','number','600','min="0" max="3600" required'):
    fileField('Reference orbit','reference','.oem,.kvn,.txt','OEM (KVN/XML), or a state table with explicit column mapping. Declare frame and clock.')+`<label class="field">What is this reference?<select id="reference-kind" required><option value="">Choose its meaning</option><option value="prediction">Another prediction</option><option value="reconstructed">Reconstructed orbit</option><option value="navigation">Navigation solution</option></select><small>A prediction can establish consistency; it cannot establish the true orbit.</small></label>`+fileField('Prediction to check','prediction','.oem,.kvn,.txt,.json','OEM, OMM (XML/KVN), GP JSON/CSV, legacy TLE or mapped states. The fit must predate the comparison start.')+fileField('Candidate model orbit (optional)','candidate','.oem,.kvn,.txt,.json','Compare a proposed correction against the same reference and samples.')+`<div class="field-row">${field('Catalogue number','norad','number','39452','min="1" max="999999999" required')}${field('Tolerance (km)','tol','number','1','min="0.001" max="100000" step="any" required')}</div>`+fileField('Manoeuvres (optional)','manoeuvres','.csv','CSV columns: start,end (UTC). Samples inside those intervals are excluded.')}
    ${cdm?noExample('It needs two CCSDS Conjunction Data Messages for the same event, in KVN or XML — typically an original warning and a revision from the same provider.'):''}
    ${localNote()}<div class="form-actions"><button class="primary full-width" type="submit" id="run-analysis">${cdm?'Reconcile messages':'Compare orbit files'} →</button>${cdm?'':'<button class="secondary full-width" type="button" id="run-example">Run the Swarm A example</button>'}</div><div class="status-line" id="form-status" role="status"></div></form>${cdm?'':exampleLinks(['swarm-a-esa-orbit.oem','swarm-a-elements-2024-05-12.json','swarm-a-elements-2024-05-06.json','swarm-a-esa-manoeuvres.csv'])}</section><div id="tool-result" class="result-stack">${emptyResult(cdm?'Did the event change, or did the inputs?':'The difference needs an explanation.',cdm?'Select two conjunction messages for the same event. No example is supplied.':'Choose files from your PC, or run the Swarm A example: ESA reconstructed orbit against two real element sets six days apart.')}</div></div>`;
  mountScene();prepareImports(cdm?[]:['reference','prediction','candidate']);$('setup-tool').onclick=setup;
  document.querySelectorAll<HTMLButtonElement>('[data-orbit-mode]').forEach(b=>b.onclick=()=>{orbitMode=b.dataset.orbitMode!;generation++;orbits();});
  $('analysis-form').onsubmit=async(e)=>{e.preventDefault();const status=$('form-status'),button=$<HTMLButtonElement>('run-analysis');try{const body=cdm?{first:await readFile('first'),second:await readFile('second'),tolerance_s:nval('tca-tolerance')}:{reference:await readFile('reference'),prediction:await readFile('prediction'),candidate:await readFile('candidate',false),manoeuvres:await readFile('manoeuvres',false),reference_kind:val('reference-kind'),norad:nval('norad'),tolerance_km:nval('tol'),reference_import:importOptions('reference'),prediction_import:importOptions('prediction'),candidate_import:importOptions('candidate')};await runRequest(cdm?'cdms':'compare',body,cdm?drawCdm:drawOrbits,status,button);}catch(err){status.className='error';status.textContent=(err as Error).message;}};
  if(!cdm)$('run-example').onclick=()=>void example('compare',drawOrbits);
}
function drawOrbits(r:any):void{
  const s=r.summary;const rows=r.samples as any[];const step=Math.max(1,Math.ceil(rows.length/180));const points=rows.filter((_,i)=>i%step===0||i===rows.length-1);
  $('tool-result').innerHTML=(r.demonstration?`<div class="notice">${esc(r.demonstration)}</div>`:'')+`<div class="metrics">${metric('Median position difference',`${num(s.median_km)} <small>km</small>`,`${num(s.n,0)} correlated samples · ${num(s.sample_step_s,0)} second spacing`)}${metric('Within your tolerance',`${num(s.within_tolerance_fraction*100,0)}<small>%</small>`,`${num(s.tolerance_km)} km · reference is ${esc(r.reference_kind)}`,s.within_tolerance_fraction>=.95?'good':'warn')}</div>${scene('Earth-fixed tracks · first 100 minutes · distances are not exaggerated')}<section class="card"><div class="card-head"><div><h2>How the products separate</h2><p class="card-sub">Three-dimensional distance from the declared reference</p></div></div>${chart([{label:'Prediction',colour:'#61dfff',values:points.map(p=>[p.elapsed_h,p.distance_km])},...(s.candidate_median_km!=null?[{label:'Candidate model',colour:'#c4f563',values:points.map(p=>[p.elapsed_h,p.candidate_km] as [number,number])}]:[])],'Elapsed time in overlap (hours)','Position difference (km)')}<div class="decision"><strong>What this changes</strong>${s.p95_km>s.tolerance_km?'The 95th percentile exceeds your tolerance. Review the orbit source or request a fresher product before using it for this task.':'The 95th percentile is inside your tolerance over these samples. Check the reference quality and the unsampled intervals before adopting it.'}${s.candidate_median_km!=null?` The candidate reduces the difference in ${num(s.candidate_fraction_better*100,0)}% of paired samples.`:''} ${r.reference_kind==='prediction'?'Both files are predictions: this measures agreement, not accuracy.':''}</div></section><section class="card"><div class="card-head"><div><h2>Reference conventions</h2><p class="card-sub">${esc(r.start)} → ${esc(r.end)}</p></div></div><div class="table-scroll"><table><thead><tr><th>Product</th><th>Frame</th><th>Clock</th><th>Format</th></tr></thead><tbody>${r.metadata.map((m:any)=>`<tr><td>${esc(m.name)}</td><td>${esc(m.frame)}</td><td>${esc(m.time_system)}</td><td>${esc(m.format)}</td></tr>`).join('')}</tbody></table></div></section><details class="card details-panel"><summary>Inspect samples · ${num(rows.length,0)} total</summary><div class="details-body"><p>First 40 shown. The CSV contains every sample. Radial is towards or away from Earth; along-track follows the orbit; cross-track is sideways out of the orbit plane.</p><div class="table-scroll"><table><thead><tr><th>UTC</th><th>Radial km</th><th>Along-track km</th><th>Cross-track km</th></tr></thead><tbody>${rows.slice(0,40).map(p=>`<tr><td>${esc(p.time)}</td><td>${num(p.radial_km,3)}</td><td>${num(p.in_track_km,3)}</td><td>${num(p.cross_track_km,3)}</td></tr>`).join('')}</tbody></table></div></div></details>${exportButtons()}${sourceDetails(r)}`;
  mountScene(s.earth_tracks||[]);bindExports(r,rows);
}
function drawCdm(r:any):void{
  $('tool-result').innerHTML=(r.demonstration?`<div class="notice">${esc(r.demonstration)}</div>`:'')+`<div class="metrics">${metric('Pair and time match',r.same_case?'Same case':'Unresolved',`Time tolerance: ${num(r.tolerance_s,0)} seconds`,r.same_case?'good':'warn')}${metric('Change in closest-approach time',`${num(r.tca_delta_s,1)} <small>s</small>`,'Second message minus first message')}</div>${scene('Earth context · conjunction messages alone do not define a plotted orbit')}<section class="card"><div class="card-head"><div><h2>What changed between messages?</h2><p class="card-sub">These values are read from the messages; they are not recomputed.</p></div></div><div class="table-scroll"><table><thead><tr><th>File</th><th>Closest approach (UTC)</th><th>Miss distance</th><th>Collision probability</th></tr></thead><tbody>${r.messages.map((m:any)=>`<tr><td>${esc(m.source)}</td><td>${esc(m.tca)}</td><td>${num(m.miss_distance_m)} m</td><td>${typeof m.collision_probability==='number'?m.collision_probability.toExponential(2):'Not supplied'}</td></tr>`).join('')}</tbody></table></div><div class="decision"><strong>What this changes</strong>${r.same_case?'Reconcile the orbit versions, uncertainty and hard-body radius before explaining the change as an increased physical risk.':'Resolve the object pair or time difference before comparing probabilities as if these were the same event.'}</div></section><section class="card"><div class="card-head"><h2>Uncertainty checks</h2></div><div class="table-scroll"><table><thead><tr><th>File / object</th><th>Frame</th><th>Position covariance</th></tr></thead><tbody>${r.checks.map((c:any)=>`<tr><td>${esc(c.file)} / ${esc(c.object)}</td><td>${esc(c.frame)}</td><td>${esc(c.covariance)}</td></tr>`).join('')}</tbody></table></div></section>${exportButtons()}${sourceDetails(r)}`;mountScene();bindExports(r,r.messages);
}

function contacts():void{
  if(contactMode==='plan'){planner();return;}
  $('content').innerHTML=header('Ground-contact experiment','Will the next pass start where you expect?','Compare predicted visibility with receiver lock times. Test whether a different orbit file changes the schedule before changing a ground-station procedure.',actions())+planningTabs()+`<div class="tool-grid"><section class="card input-card"><form id="analysis-form"><h3>Station and orbit</h3>${fileField('Orbit prediction','prediction','.json,.oem,.kvn,.txt','OEM, OMM, GP JSON/CSV, TLE or mapped states. One fixed orbit version is used.')}${fileField('Alternative orbit (optional)','candidate','.json,.oem,.kvn,.txt','Compare acquisition times from a different orbit version.')}${fileField('Receiver log (optional)','lock-log','.csv','CSV column: lock_time (UTC). Extra columns are ignored.')}<div class="field-row">${field('Latitude (°)','lat','number','-25.890','min="-90" max="90" step="any" required')}${field('Longitude (°)','lon','number','27.687','min="-180" max="180" step="any" required')}</div><p class="card-sub">IGS station HRAO00ZAF at Hartebeesthoek, from the published IGS station list: a surveyed geodetic marker, not a statement about which antenna is used or whether the site is available. Enter your own station coordinates.</p><div class="field-row">${field('Height (m)','height','number','1414.744','min="-500" max="9000" step="any" required')}${field('Elevation mask (°)','mask','number','10','min="0" max="89" step="any" required')}</div>${field('Window start (UTC)','start','datetime-local','2024-05-11T00:00','required')}<div class="field-row">${field('Window (hours)','hours','number','24','min="1" max="48" required')}${field('Catalogue number','norad','number','25544','min="1" max="999999999" required')}</div>${localNote()}<div class="form-actions"><button class="primary" id="run-analysis" type="submit">Calculate contacts →</button><button class="secondary" id="run-example" type="button">Run the ISS example</button></div><div id="form-status" class="status-line" role="status"></div></form>${exampleLinks(['iss-elements-2024-05-10.json','iss-elements-2024-05-04.json'])}</section><div id="tool-result" class="result-stack">${emptyResult('A pass is more than a predicted time.','Choose files from your PC, or run the ISS example over the published position of IGS station HRAO00ZAF.')}</div></div>`;
  bindPlanningTabs();prepareImports(['prediction','candidate']);mountScene([], {lat:-25.890,lon:27.687});$('setup-tool').onclick=setup;$('run-example').onclick=()=>void example('contacts',drawContacts);
  $('analysis-form').onsubmit=async(e)=>{e.preventDefault();const status=$('form-status');try{const body={prediction:await readFile('prediction'),candidate:await readFile('candidate',false),log:await readFile('lock-log',false),latitude:nval('lat'),longitude:nval('lon'),height_m:nval('height'),mask_deg:nval('mask'),start:val('start')+'Z',hours:nval('hours'),norad:nval('norad'),prediction_import:importOptions('prediction'),candidate_import:importOptions('candidate')};await runRequest('contacts',body,drawContacts,status,$<HTMLButtonElement>('run-analysis'));}catch(err){status.className='error';status.textContent=(err as Error).message;}};
}
function contactTime(value:string, date=true):string{const t=new Date(Math.round(Date.parse(value)/1000)*1000).toISOString();return date?t.slice(0,19).replace('T',' '):t.slice(11,19);}
function drawContacts(r:any):void{
  const p=r.passes as any[];const matched=p.filter(x=>x.lock_time).length;const first=r.first_pass_samples as any[];
  $('tool-result').innerHTML=(r.demonstration?`<div class="notice">${esc(r.demonstration)}</div>`:'')+`<div class="metrics">${metric('Detected contacts',`${num(p.length,0)}`,`${num(r.hours,0)} hours · ${num(r.mask_deg,0)}° minimum elevation`)}${metric('Receiver records matched',`${num(matched,0)}`,`${num(r.unmatched_lock_times.length,0)} unresolved log rows`)}</div>${scene('Earth-fixed prediction track near the first detected contact')}<section class="card"><div class="card-head"><div><h2>First contact: height above the horizon</h2><p class="card-sub">Geometric visibility, before weather or radio-link effects</p></div></div>${chart([{label:'Elevation',colour:'#cbe99f',values:first.map(v=>[v.minutes_from_aos,v.elevation_deg])},{label:'Station mask',colour:'#c4f563',values:first.map(v=>[v.minutes_from_aos,r.mask_deg]),dashed:true}],'Minutes from predicted acquisition','Elevation (degrees)')}<div class="decision"><strong>What this changes</strong>Use the paired orbit timings to test your update policy. Investigate late lock against clock, pointing and link conditions; it does not by itself prove an orbit error. ${p.some(x=>x.partial)?'Partial passes are cut by the chosen window or missing orbit coverage.':''}</div></section><section class="card"><div class="card-head"><div><h2>Contact timeline</h2><p class="card-sub">Times rounded to seconds. Alternative Δ = alternative acquisition minus baseline acquisition.</p></div></div><div class="table-scroll"><table><thead><tr><th>Acquisition (UTC)</th><th>Loss (UTC)</th><th>Peak</th><th>Lock delay</th><th>Alternative Δ</th></tr></thead><tbody>${p.map(x=>`<tr><td>${esc(contactTime(x.aos))}${x.partial?' · partial':''}</td><td>${esc(contactTime(x.los,false))}</td><td>${num(x.peak_elevation_deg,1)}°</td><td>${x.lock_delay_s==null?'Not matched':num(x.lock_delay_s,1)+' s'}</td><td>${x.alternative_aos_delta_s==null?'Not matched':num(x.alternative_aos_delta_s,1)+' s'}</td></tr>`).join('')||'<tr><td colspan="5">No contact detected. Check orbit coverage, station coordinates, time window and elevation mask.</td></tr>'}</tbody></table></div></section>${r.unmatched_lock_times.length?`<div class="notice">Unmatched receiver times: ${r.unmatched_lock_times.map(esc).join(', ')}. These are unresolved, not automatically missed passes.</div>`:''}${exportButtons()}${sourceDetails(r)}`;
  mountScene(r.metadata.earth_tracks||[],r.station);bindExports(r,p);
  const planExport=document.createElement('button');planExport.className='secondary';planExport.textContent='Use complete passes in a plan ↓';document.querySelector('#tool-result .export-actions')?.append(planExport);planExport.onclick=()=>download('candidate-contacts.csv',csv(p.filter(x=>!x.partial).map((x,i)=>({contact_id:String(r.norad||'orbit')+'-'+String(i+1),satellite:String(r.norad||'Selected spacecraft'),start:x.aos,end:x.los,priority:1}))),'text/csv;charset=utf-8');
}

const cases=[
  {title:'A 137 km jump',tag:'Clock conventions',description:'The same orbit appears far apart before a manoeuvre is considered.',facts:['The Swarm precise-orbit epochs used GPS time.','The comparison initially treated those epochs as UTC.','An 18-second offset accounted for roughly 137 km along the orbit in the corrected project analysis.'],question:'What should the analyst do first?',options:['Convert both time systems correctly and rerun the comparison.','Label the residual as an unexplained manoeuvre.','Increase the covariance until the discrepancy appears acceptable.'],correct:0,next:'Record the time conversion and keep both results. A clock mismatch must be resolved before investigating dynamics.',source:'docs/calibration-benchmark.md · GPS/UTC correction, 2026-09-05'},
  {title:'The 36 km frame error',tag:'Coordinate conventions',description:'Reading a precise file in the wrong frame defeats its precision.',facts:['The SpaceX file convention was identified as MEME/J2000 from its filename.','Treating those states as TEME produced a positional mismatch of about 36 km.','An orbit-fit residual near 0.2 km does not validate the reader’s frame conversion.'],question:'Which statement is supported?',options:['The operator states establish an independently observed orbit.','The reader must verify and convert the frame before interpreting residuals.','The 36 km discrepancy establishes abnormal spacecraft behaviour.'],correct:1,next:'Preserve the raw filename and metadata, use the documented frame conversion and rerun the same epochs. Identify any remaining unknowns.',source:'docs/ephemeris-frame.md and docs/spacex-ephemerides.md'},
  {title:'Two predictions disagree',tag:'Limits of evidence',description:'An 83 km difference sounds decisive. Its reference still matters.',facts:['SGP4 fits and matched operator ephemerides separate by about 83 km towards the end of a 72-hour file in the reported sample.','The operator file is a published prediction. It is not an observation of what the spacecraft later did.','Lineage checks support that the compared fits and files belong together.'],question:'What can the analyst conclude?',options:['The discrepancy proves the operator’s realised orbit was 83 km wrong.','The fit is less consistent with the operator prediction at that lead; realised error remains unknown.','The discrepancy proves hostile intent.'],correct:1,next:'Request a reconstructed orbit or navigation solution if the decision requires realised accuracy. Report prediction consistency separately from physical behaviour.',source:'docs/spacex-ephemerides.md · lineage checked 2026-09-05'}
];
function evidence():void{
  const c=cases[evidenceCase];
  $('content').innerHTML=header('Analytical evidence lab','Make the claim no stronger than the evidence.','Work through recorded data failures. Separate what was measured, what was inferred and what remains unknown.',actions())+`<div class="case-grid">${cases.map((c,i)=>`<button class="case-choice" data-case="${i}" aria-pressed="${evidenceCase===i}"><span class="case-number">CASE 0${i+1} · ${c.tag}</span><strong>${c.title}</strong><small>${c.description}</small></button>`).join('')}</div><div class="visual-analysis">${scene('Earth context · this exercise uses documented findings, not live tracking')}<section class="card card-pad"><span class="badge amber">Training exercise · answer key</span><h2 style="margin-top:18px">${c.title}</h2>${c.facts.map((f,i)=>`<div class="fact-row"><strong>Recorded fact 0${i+1}</strong>${f}</div>`).join('')}<p class="card-sub" style="margin-top:16px">Source: ${esc(c.source)}</p></section></div><section class="card card-pad"><h2>${c.question}</h2><form id="evidence-form"><div class="answer-list">${c.options.map((o,i)=>`<label class="answer-option"><input type="radio" name="answer" value="${i}" required/>${esc(o)}</label>`).join('')}</div><label class="field">Your review note<textarea id="review-note" maxlength="4000" placeholder="What is observed? Which alternatives remain? What evidence would change the decision?"></textarea></label>${fileField('Attach a local text evidence file (optional)','evidence-file','.txt,.json,.csv,.oem,.kvn,.xml','The browser records its SHA-256 and name in your report. A fingerprint is not verification of its claims.')}<button class="primary" type="submit">Check the reasoning →</button></form><div id="reasoning-result" role="status"></div></section>`;
  mountScene();$('setup-tool').onclick=setup;document.querySelectorAll<HTMLButtonElement>('[data-case]').forEach(b=>b.onclick=()=>{evidenceCase=Number(b.dataset.case);generation++;evidence();});
  $('evidence-form').onsubmit=async(e)=>{e.preventDefault();const g=generation;const choice=Number((document.querySelector('input[name=answer]:checked') as HTMLInputElement).value);const note=$<HTMLTextAreaElement>('review-note').value;let evidenceFile=null;try{const f=await readFile('evidence-file',false);if(f){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(f.text));evidenceFile={name:f.name,sha256:Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join(''),status:'fingerprinted only; content not validated'};}}catch(err){$('reasoning-result').textContent=(err as Error).message;return;}if(g!==generation)return;const ok=choice===c.correct;const report={kind:'evidence-exercise',built_at:new Date().toISOString(),case:c.title,source:c.source,recorded_facts:c.facts,answer:c.options[choice],matches_answer_key:ok,next_action:c.next,review_note:note,attached_evidence:evidenceFile,limits:'This scores a documented training case, not an intelligence assessment or a new operational event.'};$('reasoning-result').innerHTML=`<div class="${ok?'success-note':'notice'}"><strong>${ok?'The claim fits the evidence.':'That claim needs revision.'}</strong><p>${esc(c.next)}</p><p>The supported answer: ${esc(c.options[c.correct])}</p><button class="secondary" id="export-exercise">Save review JSON ↓</button></div>`;$('export-exercise').onclick=()=>download('driftwatch-evidence-exercise.json',report);};
}


function planningTabs(): string {
  return `<div class="toolbar"><div class="segmented" role="group" aria-label="Ground-contact tool"><button data-contact-mode="visibility" aria-pressed="${contactMode === 'visibility'}">Predict visibility</button><button data-contact-mode="plan" aria-pressed="${contactMode === 'plan'}">Plan one antenna</button></div><span class="card-sub">Local analysis · no antenna commands</span></div>`;
}
function bindPlanningTabs(): void {
  document.querySelectorAll<HTMLButtonElement>('[data-contact-mode]').forEach(button => button.onclick = () => {
    contactMode = button.dataset.contactMode!; generation++; contacts();
  });
}
function planner(): void {
  const labels: Record<string,string> = {contact_id:'Contact ID', satellite:'Satellite', start:'Start time', end:'End time', priority:'Priority', baseline:'Current schedule (optional)', locked:'Protected contact (optional)'};
  const keys = Object.keys(labels);
  const optional = (key:string) => key === 'baseline' || key === 'locked';
  $('content').innerHTML = header('Ground contacts / schedule review', 'Is the change worth making?', 'Compare a proposed contact plan with the schedule you already accepted. Protect commitments, see the trade-offs and review every addition or removal.', actions()) + planningTabs() + `
    <div class="tool-grid"><section class="card input-card"><form id="analysis-form"><h3>One antenna. Your requests.</h3>
      ${fileField('Contact request table', 'plan-file', '.csv,.tsv,.txt', 'One row per feasible pass, including both accepted and unaccepted requests. Times need ISO 8601 with Z or a UTC offset.')}
      <details class="import-options"><summary>Column mapping and separator</summary>
        <label class="field">Separator<select id="plan-separator"><option value=",">Comma</option><option value=";">Semicolon</option><option value="tab">Tab</option></select></label>
        <div id="plan-mapping">${keys.map(k => `<label class="field">${labels[k]} column<input id="map-${k}" value="${optional(k)?'':k}" placeholder="${optional(k)?'Optional column name':''}"/></label>`).join('')}</div>
      </details>
      ${field('Turnaround between contacts (seconds)', 'plan-turnaround', 'number', '60', 'min="0" max="3600" step="any" required')}
      <div class="plan-guidance"><p><strong>Current schedule</strong>Add a <code>baseline</code> column. Mark already accepted contacts <code>true</code>; the rest <code>false</code>.</p><p><strong>Protected contacts</strong>Add <code>locked</code> and mark commitments that must stay <code>true</code>. Conflicting protected contacts stop the calculation.</p><p>Priority is your relative preference: 6 + 6 outweighs 10. Equal-priority plans preserve as much of your current schedule as possible. A fixed turnaround approximates antenna movement.</p></div>
      ${noExample('It needs one week of your real contact requests as CSV or TSV: <code>contact_id,satellite,start,end,priority</code>, with optional <code>baseline</code> and <code>locked</code> flags. Times need ISO 8601 with Z or a UTC offset.')}
      ${localNote()}<div class="form-actions"><button class="primary" id="run-analysis" type="submit">Review this schedule →</button></div><div id="form-status" class="status-line" role="status"></div>
    </form></section><div id="tool-result" class="result-stack">${emptyResult('A changed schedule needs a reason.','Supply your own request table. No example is supplied, and the planner has not been run against a real request week.')}</div></div>`;
  mountScene(); bindPlanningTabs(); $('setup-tool').onclick = setup;
  const invalidateReview = () => {
    generation++;
    $('tool-result').innerHTML = '<div class="notice">Inputs changed. Run the schedule review to see a result for these settings.</div>';
    $('form-status').className = 'status-line';
    $('form-status').textContent = 'The previous review has been cleared.';
  };
  let columnRevision = 0;
  const updateColumns = async () => {
    const revision = ++columnRevision, input = $('plan-file');
    const button = $<HTMLButtonElement>('run-analysis'); button.disabled = true;
    try {
      const file = await readFile('plan-file', false); if (!file || !$('plan-mapping')) return;
      if (revision !== columnRevision || input !== $('plan-file')) return;
      const delimiter = val('plan-separator') === 'tab' ? '\t' : val('plan-separator');
      const columns = tableHeadings(file.text, delimiter);
      $('plan-mapping').innerHTML = keys.map(k => `<label class="field">${labels[k]} column<select id="map-${k}"><option value="">${optional(k)?'Not supplied':'Choose column'}</option>${columns.map(c => `<option value="${esc(c)}" ${c === k ? 'selected' : ''}>${esc(c)}</option>`).join('')}</select></label>`).join('');
    } finally { if (revision === columnRevision && button.isConnected) button.disabled = false; }
  };
  $('plan-file').onchange = () => { invalidateReview(); void updateColumns().catch(e => { $('form-status').textContent = e.message; }); };
  $('plan-separator').onchange = () => { invalidateReview(); void updateColumns().catch(e => { $('form-status').textContent = e.message; }); };
  $('analysis-form').oninput = e => {
    if (!['plan-file','plan-separator'].includes((e.target as HTMLElement).id)) invalidateReview();
  };
  $('analysis-form').onsubmit = async e => {
    e.preventDefault(); invalidateReview(); const status = $('form-status');
    try {
      await runRequest('plan', {contacts: await readFile('plan-file'), turnaround_s: nval('plan-turnaround'), delimiter: val('plan-separator') === 'tab' ? '\t' : val('plan-separator'), mapping: Object.fromEntries(keys.map(k => [k, val(`map-${k}`)]))}, drawPlan, status, $<HTMLButtonElement>('run-analysis'));
    } catch (error) { status.className = 'error'; status.textContent = (error as Error).message; }
  };
}
function drawPlan(result: any): void {
  const rows = result.contacts as any[];
  const start = Math.min(...rows.map(c => c.start_s)), end = Math.max(...rows.map(c => c.end_s));
  const comparison = result.comparison;
  const hasBaseline = comparison?.provided;
  const reviewStatus = comparison?.status || 'baseline_required';
  const heading = reviewStatus === 'improved' ? `${num(comparison.priority_delta)} more priority points. Review the changes.` : reviewStatus === 'unchanged' ? 'Keep the current schedule.' : reviewStatus === 'repair_required' ? 'The current schedule needs repair.' : 'Supply the current schedule to measure a gain.';
  const explanation = reviewStatus === 'improved' ? 'Review the proposed removals with their owners before accepting additions. The gain uses your priorities; it does not establish more data delivered or higher revenue.' : reviewStatus === 'unchanged' ? 'Your accepted contacts already maximise the declared priorities under these constraints. An equal-scoring alternative is not a reason to disrupt the schedule.' : reviewStatus === 'repair_required' ? 'The declared current schedule conflicts with the timing or commitments. The proposed plan satisfies this model, but comparing its score with an infeasible plan would misstate an improvement.' : 'The proposed plan is feasible under the declared constraints. Earliest-start first is only a reference rule; it is not evidence of improvement over your procedure.';
  const changeLabels: Record<string,string> = {retained:'Keep',added:'Proposed addition',removed:'Proposed removal',not_selected:'Not selected',selected:'Selected'};
  const ids = (values:string[]) => `${values.slice(0,8).map(esc).join(', ')}${values.length>8?` · ${values.length-8} more in the table`:''}`;
  const countLabel = (count:number, noun:string) => `${count} ${noun}${count===1?'':'s'}`;
  const inputRows = rows.map(c => ({contact_id:c.contact_id, satellite:c.satellite, start:c.start, end:c.end, priority:c.priority, ...(hasBaseline?{baseline:c.baseline}:{}), locked:!!c.locked, resource:result.resource}));
  $('tool-result').innerHTML = (result.demonstration ? `<div class="notice">${esc(result.demonstration)}</div>` : '') + `
    <section class="card plan-review"><div class="card-head"><div><p class="eyebrow">SCHEDULE COMPARISON</p><h2>${heading}</h2></div><span class="badge ${reviewStatus==='repair_required'?'amber':''}">${num(result.protected_count||0)} protected</span></div>
      <div class="plan-summary"><p>${explanation}</p>${comparison?.issues?.length?`<div class="error"><strong>Resolve these declarations</strong><ul>${comparison.issues.map((issue:string)=>`<li>${esc(issue)}</li>`).join('')}</ul></div>`:''}
      ${hasBaseline?`<div class="table-scroll"><table><thead><tr><th>Plan</th><th>Contacts</th><th>Priority points</th><th>Contact minutes</th></tr></thead><tbody><tr><th>Current${comparison.feasible?'':' · infeasible'}</th><td>${num(comparison.baseline_count)}</td><td>${num(comparison.baseline_priority)}</td><td>${num(comparison.baseline_minutes,1)}</td></tr><tr><th>Proposed</th><td>${num(result.selected_count)}</td><td>${num(result.priority_total)}</td><td>${num(comparison.proposed_minutes,1)}</td></tr></tbody></table></div><div class="plan-changes"><div><strong>${countLabel(comparison.added_ids.length,'addition')}</strong><span>${ids(comparison.added_ids)||'None'}</span></div><div><strong>${countLabel(comparison.removed_ids.length,'removal')}</strong><span>${ids(comparison.removed_ids)||'None'}</span></div><div><strong>${comparison.retained_ids.length} retained</strong><span>${ids(comparison.retained_ids)||'None'}</span></div></div>`:`<p class="card-sub">Mark accepted contacts in a <code>baseline</code> column, then rerun the complete request table.</p>`}
      </div><div class="decision"><strong>Before changing the station schedule</strong>Check visibility, radio readiness, actual slew requirements and the completeness of the request table. This review sends no antenna commands or booking changes.</div>
    </section>
    <div class="metrics">${metric('Proposed contacts', `${num(result.selected_count, 0)} <small>of ${rows.length}</small>`, `${num(result.turnaround_s)} seconds between whole passes`, 'good')}${metric('Proposed priority', num(result.priority_total), `${num(result.first_come_priority)} with earliest-start first under the same commitments · preference units`)}</div>
    <section class="card"><div class="card-head"><div><h2>Every request has a place.</h2><p class="card-sub">${contactTime(new Date(start*1000).toISOString())} → ${contactTime(new Date(end*1000).toISOString())} UTC</p></div><span class="badge">${esc(result.resource)}</span></div>
      <div class="timeline" aria-label="Contact request timeline; exact times and decisions follow in the table">${rows.map(c => {const position=`left:${(c.start_s-start)/(end-start)*100}%;width:${(c.end_s-c.start_s)/(end-start)*100}%`;return `<div class="timeline-row"><span>${esc(c.contact_id)}<br/><small>${c.locked?'Protected · ':''}${esc(c.satellite)}</small></span><div class="timeline-track"><div class="timeline-bar ${c.selected?'':'excluded'}" style="${position}" title="${esc(c.start)} — ${esc(c.end)} · ${c.selected?'Proposed':'Not selected'}"></div>${c.baseline?`<div class="timeline-current" style="${position}" title="In the supplied current schedule"></div>`:''}</div></div>`;}).join('')}</div>
      <div class="legend"><span><i></i>Proposed</span><span><i style="background:#516576"></i>Not selected · dashed border</span>${hasBaseline?'<span><i style="background:var(--cyan)"></i>Current · underline</span>':''}</div>
    </section>
    <section class="card"><div class="card-head"><h2>Decision for every request</h2></div><div class="table-scroll"><table><thead><tr><th>Contact / satellite</th><th>Start (UTC)</th><th>End (UTC)</th><th>Priority</th><th>Commitment</th><th>Change</th><th>Reason</th></tr></thead><tbody>${rows.map(c=>`<tr><td>${esc(c.contact_id)} / ${esc(c.satellite)}</td><td>${contactTime(c.start)}</td><td>${contactTime(c.end)}</td><td>${num(c.priority)}</td><td>${c.locked?'Protected':'Flexible'}</td><td class="${c.change==='removed'?'warn':c.selected?'good':''}">${changeLabels[c.change]|| (c.selected?'Selected':'Not selected')}</td><td>${c.selected?esc(c.decision):'Conflicts with '+c.conflicts_with.map(esc).join(', ')}</td></tr>`).join('')}</tbody></table></div></section>
    ${exportButtons()}<div class="export-actions no-print"><button class="secondary" id="export-plan-input">Save request table CSV ↓</button><button class="secondary" id="export-plan-selected">Save proposed contacts CSV ↓</button></div><p class="card-sub">Request table: edit priorities or flags and rerun. Proposed contacts: selected rows only, for review before booking. Evidence JSON retains the complete comparison.</p>${sourceDetails(result)}`;
  bindExports(result, rows.map(c => ({contact_id:c.contact_id, satellite:c.satellite, start:c.start, end:c.end, priority:c.priority, baseline:hasBaseline?c.baseline:null, protected:!!c.locked, proposed:c.selected, change:c.change, decision:c.decision, conflicts_with:c.conflicts_with.join('; ')})));
  $('export-plan-input').onclick = () => download('driftwatch-contact-requests.csv',csv(inputRows),'text/csv;charset=utf-8');
  $('export-plan-selected').onclick = () => download('driftwatch-proposed-contacts.csv',csv(inputRows.filter((_,i)=>rows[i].selected)),'text/csv;charset=utf-8');
}
